# Generated by Django 3.0.6 on 2020-06-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogPost',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='blogPost',
            new_name='Post',
        ),
    ]
